### ISSUE TITLE
Maintain DHCP lease.

### ISSUE THREAD

**Issue by yunjova** [PavSedl/RAILDUINO#1]
To be sure that no other device on the network gets the IP address of a Railduino from the DHCP server after the lease time is expired, it is necessary to call "Ethernet.maintain()" on a regular basis.
See also: https://www.arduino.cc/en/Reference/EthernetMaintain and https://www.arduino.cc/en/Reference/EthernetBegin.
Kind regards.

**Comment by PavSedl** [comment]
Already done
